import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import './index.css';

// 1. Import Amplify and your configuration file
import { Amplify } from 'aws-amplify';
import awsExports from './aws-exports.js'; // This file is generated by Amplify

// 2. Call Amplify.configure() at the top level, before rendering the app
Amplify.configure(awsExports);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);